### ISSUE TITLE
AsMessage (string) and null

### ISSUE THREAD

**Issue by fjenett** [velcrome/vvvv-Message#2] opened 2015-04-24 11:04 UTC
I have trouble parsing JSON strings containing ```null``` with AsMessage (string).

```
{
  "a_value":null
}
```

**Comment by velcrome** [comment] 2015-04-24 12:01
What would be the expected behaviour? 

I think skipping it would be the most reasonable answer, since we cannot even deduce a meaningful type from that property.

**Comment by velcrome** [comment] 2015-04-24 12:43
fixed in master.

**Closed by velcrome** 2015-04-24 12:43 UTC
Labels: bug

**Comment by velcrome** [comment] 2015-04-24 13:17
replacement dll (for /core and /plugins directories) can be found [https://www.nuget.org/packages/VVVV.Packs.Message/](here)
